=== sszemer/mySerenityProject/src/test/resources/REST/schemas/nbp.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://api.nbp.pl/api/exchangerates/tables/A/?format=json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "table",
      "no",
      "effectiveDate",
      "rates"
    ],
    "properties": {
      "table": {
        "$id": "#/items/properties/table",
        "type": "string",
        "title": "The Table Schema",
        "default": "",
        "examples": [
          "A"
        ],
        "pattern": "^(.*)$"
      },
      "no": {
        "$id": "#/items/properties/no",
        "type": "string",
        "title": "The No Schema",
        "default": "",
        "examples": [
          "022/A/NBP/2020"
        ],
        "pattern": "^(.*)$"
      },
      "effectiveDate": {
        "$id": "#/items/properties/effectiveDate",
        "type": "string",
        "title": "The Effectivedate Schema",
        "default": "",
        "examples": [
          "2020-02-03"
        ],
        "pattern": "^(.*)$"
      },
      "rates": {
        "$id": "#/items/properties/rates",
        "type": "array",
        "title": "The Rates Schema",
        "items": {
          "$id": "#/items/properties/rates/items",
          "type": "object",
          "title": "The Items Schema",
          "required": [
            "currency",
            "code",
            "mid"
          ],
          "properties": {
            "currency": {
              "$id": "#/items/properties/rates/items/properties/currency",
              "type": "string",
              "title": "The Currency Schema",
              "default": "",
              "examples": [
                "bat (Tajlandia)"
              ],
              "pattern": "^(.*)$"
            },
            "code": {
              "$id": "#/items/properties/rates/items/properties/code",
              "type": "string",
              "title": "The Code Schema",
              "default": "",
              "examples": [
                "THB"
              ],
              "pattern": "^(.*)$"
            },
            "mid": {
              "$id": "#/items/properties/rates/items/properties/mid",
              "type": "number",
              "title": "The Mid Schema",
              "default": 0.0,
              "examples": [
                0.1251
              ]
            }
          }
        }
      }
    }
  }
}

=== sszemer/mySerenityProject/src/test/resources/REST/responses/scratch.json
[
  {
    "table": "A",
    "no": "022/A/NBP/2020",
    "effectiveDate": "2020-02-03",
    "rates": [
      {
        "currency": "bat (Tajlandia)",
        "code": "THB",
        "mid": 0.1251
      },
      {
        "currency": "dolar amerykański",
        "code": "USD",
        "mid": 3.8864
      },
      {
        "currency": "dolar australijski",
        "code": "AUD",
        "mid": 2.6030
      },
      {
        "currency": "dolar Hongkongu",
        "code": "HKD",
        "mid": 0.5004
      },
      {
        "currency": "dolar kanadyjski",
        "code": "CAD",
        "mid": 2.9340
      },
      {
        "currency": "dolar nowozelandzki",
        "code": "NZD",
        "mid": 2.5121
      },
      {
        "currency": "dolar singapurski",
        "code": "SGD",
        "mid": 2.8404
      },
      {
        "currency": "euro",
        "code": "EUR",
        "mid": 4.3034
      },
      {
        "currency": "forint (Węgry)",
        "code": "HUF",
        "mid": 0.01273
      },
      {
        "currency": "frank szwajcarski",
        "code": "CHF",
        "mid": 4.0311
      },
      {
        "currency": "funt szterling",
        "code": "GBP",
        "mid": 5.0844
      },
      {
        "currency": "hrywna (Ukraina)",
        "code": "UAH",
        "mid": 0.1551
      },
      {
        "currency": "jen (Japonia)",
        "code": "JPY",
        "mid": 0.035817
      },
      {
        "currency": "korona czeska",
        "code": "CZK",
        "mid": 0.1707
      },
      {
        "currency": "korona duńska",
        "code": "DKK",
        "mid": 0.5759
      },
      {
        "currency": "korona islandzka",
        "code": "ISK",
        "mid": 0.031435
      },
      {
        "currency": "korona norweska",
        "code": "NOK",
        "mid": 0.4195
      },
      {
        "currency": "korona szwedzka",
        "code": "SEK",
        "mid": 0.4031
      },
      {
        "currency": "kuna (Chorwacja)",
        "code": "HRK",
        "mid": 0.5780
      },
      {
        "currency": "lej rumuński",
        "code": "RON",
        "mid": 0.9003
      },
      {
        "currency": "lew (Bułgaria)",
        "code": "BGN",
        "mid": 2.2003
      },
      {
        "currency": "lira turecka",
        "code": "TRY",
        "mid": 0.6493
      },
      {
        "currency": "nowy izraelski szekel",
        "code": "ILS",
        "mid": 1.1275
      },
      {
        "currency": "peso chilijskie",
        "code": "CLP",
        "mid": 0.004856
      },
      {
        "currency": "peso filipińskie",
        "code": "PHP",
        "mid": 0.0764
      },
      {
        "currency": "peso meksykańskie",
        "code": "MXN",
        "mid": 0.2059
      },
      {
        "currency": "rand (Republika Południowej Afryki)",
        "code": "ZAR",
        "mid": 0.2599
      },
      {
        "currency": "real (Brazylia)",
        "code": "BRL",
        "mid": 0.9075
      },
      {
        "currency": "ringgit (Malezja)",
        "code": "MYR",
        "mid": 0.9447
      },
      {
        "currency": "rubel rosyjski",
        "code": "RUB",
        "mid": 0.0608
      },
      {
        "currency": "rupia indonezyjska",
        "code": "IDR",
        "mid": 0.0002828
      },
      {
        "currency": "rupia indyjska",
        "code": "INR",
        "mid": 0.05437
      },
      {
        "currency": "won południowokoreański",
        "code": "KRW",
        "mid": 0.003255
      },
      {
        "currency": "yuan renminbi (Chiny)",
        "code": "CNY",
        "mid": 0.5535
      },
      {
        "currency": "SDR (MFW)",
        "code": "XDR",
        "mid": 5.3615
      }
    ]
  }
]
